spring:
  application:
    name: redis-distributed-lock
  data:
    redis:
      host: localhost
      port: 6379
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      redisLock:
        baseConfig: default